// src/components/Boot.svelte
<script>
  import { onMount } from 'svelte';
  import { BOOT_LINES } from '../data.js';

  let { ondone } = $props();

  let lines = $state([]);
  let gone = $state(false);
  let done = false;

  function finish() {
    if (done) return;
    done = true;
    gone = true;
    setTimeout(ondone, 620);
  }

  onMount(() => {
    let i = 0;
    const acc = [];
    const t = setInterval(() => {
      acc.push(BOOT_LINES[i++]);
      lines = [...acc];
      if (i >= BOOT_LINES.length) { clearInterval(t); setTimeout(finish, 1300); }
    }, 480);
    return () => clearInterval(t);
  });

  const pct = $derived(Math.round((lines.length / BOOT_LINES.length) * 100));
</script>

<!-- Terminal cold-boot overlay. Click anywhere (or wait) to enter. -->
<div class={'boot' + (gone ? ' gone' : '')} onclick={finish} role="button" tabindex="0" onkeydown={(e) => e.key === 'Enter' && finish()}>
  <pre>{lines.join('\n')}<span class="blk" /></pre>
  <div class="boot-bar"><i style="width:{pct}%" /></div>
  <div class="skip">{pct < 100 ? `▌ rendering . . . ${pct}%` : '▌ projecting — [ click anywhere to enter the basement ]'}</div>
</div>

// src/components/Boot.jsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { BOOT_LINES } from '../data.js';

// Terminal cold-boot overlay. Click anywhere (or wait) to enter.
export default function Boot({ onDone }) {
  const [lines, setLines] = useState([]);
  const [gone, setGone] = useState(false);
  const done = useRef(false);

  const finish = useCallback(() => {
    if (done.current) return;
    done.current = true;
    setGone(true);
    setTimeout(onDone, 620);
  }, [onDone]);

  useEffect(() => {
    let i = 0;
    const acc = [];
    const t = setInterval(() => {
      acc.push(BOOT_LINES[i++]);
      setLines([...acc]);
      if (i >= BOOT_LINES.length) { clearInterval(t); setTimeout(finish, 1300); }
    }, 480);
    return () => clearInterval(t);
  }, [finish]);

  const pct = Math.round((lines.length / BOOT_LINES.length) * 100);

  return (
    <div className={'boot' + (gone ? ' gone' : '')} onClick={finish}>
      <pre>{lines.join('\n')}<span className="blk" /></pre>
      <div className="boot-bar"><i style={{ width: pct + '%' }} /></div>
      <div className="skip">{pct < 100 ? `▌ rendering . . . ${pct}%` : '▌ projecting — [ click anywhere to enter the basement ]'}</div>
    </div>
  );
}
