// src/components/Footer.jsx
export default function Footer() {
  return (
    <footer className="foot">
      <div className="big flick">THIS IS YOUR LIFE,<br />AND IT&rsquo;S ENDING ONE<br />MINUTE AT A TIME.</div>
      <p className="q">&ldquo;On a long enough timeline, the survival rate for everyone drops to zero.&rdquo;</p>
      <div style={{ marginTop: 40 }}><span className="regmark" /><span className="regmark" /><span className="regmark" /></div>
      <div className="foot-meta">
        THIS WEBSITE HAS NO PURPOSE · BUILT TO SCRATCH AN ITCH<br />
        AN UNAUTHORIZED HOMAGE · NOT AFFILIATED WITH ANYONE — LEAST OF ALL YOURSELF<br />
        © THE FIRST RULE · YOU MET ME AT A VERY STRANGE TIME IN MY LIFE
      </div>
    </footer>
  );
}

// src/components/Footer.svelte
<footer class="foot">
  <div class="big flick">THIS IS YOUR LIFE,<br />AND IT&rsquo;S ENDING ONE<br />MINUTE AT A TIME.</div>
  <p class="q">&ldquo;On a long enough timeline, the survival rate for everyone drops to zero.&rdquo;</p>
  <div style="margin-top: 40px"><span class="regmark"></span><span class="regmark"></span><span class="regmark"></span></div>
  <div class="foot-meta">
    THIS WEBSITE HAS NO PURPOSE · BUILT TO SCRATCH AN ITCH<br />
    AN UNAUTHORIZED HOMAGE · NOT AFFILIATED WITH ANYONE — LEAST OF ALL YOURSELF<br />
    © THE FIRST RULE · YOU MET ME AT A VERY STRANGE TIME IN MY LIFE
  </div>
</footer>
