// src/components/Hud.jsx
// Minimal cinema frame: four viewfinder brackets and one quiet label.
// Wayfinding lives in the side index; this is purely atmospheric.
export default function Hud() {
  return (
    <div className="hud" aria-hidden="true">
      <div className="br-corner tlc" /><div className="br-corner trc" />
      <div className="br-corner blc" /><div className="br-corner brc" />
      <div className="hud-tl">PROJECT MAYHEM · 1999</div>
    </div>
  );
}

// src/components/Hud.svelte
<script>
  // Minimal cinema frame: four viewfinder brackets and one quiet label.
  // Wayfinding lives in the side index; this is purely atmospheric.
</script>

<div class="hud" aria-hidden="true">
  <div class="br-corner tlc" /><div class="br-corner trc" />
  <div class="br-corner blc" /><div class="br-corner brc" />
  <div class="hud-tl">PROJECT MAYHEM · 1999</div>
</div>
