// src/components/Raymond.svelte
<section class="raymond sec">
  <span class="eyebrow rev">// human sacrifice · the back of a convenience store</span>
  <div class="ray-wrap rev">
    <div class="cctv rev">
      <img src="img/yesterday-tomorrow.jpg" alt="Security footage — convenience store rear entrance" loading="lazy" />
      <div class="cctv-ui">
        <div class="tl">CAM 04 · REAR ENTRANCE</div>
        <div class="tr"><b></b> REC</div>
        <div class="cross"></div>
        <div class="bl">15 OCT 1999 · 02:47:13</div>
        <div class="br">PAPER ST SECURITY · NTSC</div>
      </div>
    </div>
    <div>
      <p class="ray-q">YOUR DINNER WILL TASTE <span class="red">BETTER</span> THAN ANY MEAL YOU&rsquo;VE EVER EATEN.</p>
      <p class="ray-p type">Raymond K. Hessel. You were going to be a veterinarian — the form was too much, so you quit. Tyler kept your license. If you&rsquo;re not on your way to becoming one in six weeks, you&rsquo;ll be dead. Tomorrow will be the most beautiful day of Raymond K. Hessel&rsquo;s life.</p>
    </div>
  </div>
</section>

// src/components/Raymond.jsx
// Human sacrifice — framed as a convenience-store security still (CCTV monitor).
export default function Raymond() {
  return (
    <section className="raymond sec">
      <span className="eyebrow rev">// human sacrifice · the back of a convenience store</span>
      <div className="ray-wrap rev">
        <div className="cctv rev">
          <img src="img/yesterday-tomorrow.jpg" alt="Security footage — convenience store rear entrance" loading="lazy" />
          <div className="cctv-ui">
            <div className="tl">CAM 04 · REAR ENTRANCE</div>
            <div className="tr"><b /> REC</div>
            <div className="cross" />
            <div className="bl">15 OCT 1999 · 02:47:13</div>
            <div className="br">PAPER ST SECURITY · NTSC</div>
          </div>
        </div>
        <div>
          <p className="ray-q">YOUR DINNER WILL TASTE <span className="red">BETTER</span> THAN ANY MEAL YOU&rsquo;VE EVER EATEN.</p>
          <p className="ray-p type">Raymond K. Hessel. You were going to be a veterinarian — the form was too much, so you quit. Tyler kept your license. If you&rsquo;re not on your way to becoming one in six weeks, you&rsquo;ll be dead. Tomorrow will be the most beautiful day of Raymond K. Hessel&rsquo;s life.</p>
        </div>
      </div>
    </section>
  );
}
