// src/components/Reveal.svelte
<script>
  import { getContext } from 'svelte';
  import { REVEAL_STAGES } from '../data.js';

  const fx = getContext('fx');

  let stage = $state(0);
  let after = $state('');

  function onClick() {
    const i = stage >= REVEAL_STAGES.length ? 0 : stage;
    const word = REVEAL_STAGES[i];
    after = word;
    stage = i + 1;
    fx.flash(word.includes('WAKE') ? 'WAKE UP' : 'TYLER');
    fx.triggerGlitch();
  }

  const label = $derived(stage >= REVEAL_STAGES.length ? '…' : 'ARE YOU SURE?');
</script>

<section class="reveal sec" id="reveal">
  <img class="bg-still film" src="img/if-not-me.jpg" alt="" aria-hidden="true" />
  <div class="bg-tint blood"></div>
  <div class="rv-inner">
    <span class="eyebrow rev">// slowly, the realization comes</span>
    <p class="rv-q rev">ALL THE WAYS YOU WISH YOU COULD BE…<br /><span class="red">THAT&rsquo;S ME.</span></p>
    <p class="rv-sub rev">I look like you want to look. I am smart, capable, and most importantly, I am free in all the ways that you are not. If not me — then who?</p>
    <button class="rv-btn rev" onclick={onClick}>{stage === 0 ? 'ARE YOU TYLER DURDEN?' : label}</button>
    <div class="rv-after">{after}</div>
  </div>
</section>

// src/components/Reveal.jsx
import { useState } from 'react';
import { useFx } from '../context/Fx.jsx';
import { REVEAL_STAGES } from '../data.js';

export default function Reveal() {
  const fx = useFx();
  const [stage, setStage] = useState(0);
  const [after, setAfter] = useState('');

  const onClick = () => {
    const i = stage >= REVEAL_STAGES.length ? 0 : stage;
    const word = REVEAL_STAGES[i];
    setAfter(word);
    setStage(i + 1);
    fx.flash(word.includes('WAKE') ? 'WAKE UP' : 'TYLER');
    fx.triggerGlitch();
  };

  const label = stage >= REVEAL_STAGES.length ? '…' : 'ARE YOU SURE?';

  return (
    <section className="reveal sec" id="reveal">
      <img className="bg-still film" src="img/if-not-me.jpg" alt="" aria-hidden="true" />
      <div className="bg-tint blood" />
      <div className="rv-inner">
        <span className="eyebrow rev">// slowly, the realization comes</span>
        <p className="rv-q rev">ALL THE WAYS YOU WISH YOU COULD BE…<br /><span className="red">THAT&rsquo;S ME.</span></p>
        <p className="rv-sub rev">I look like you want to look. I am smart, capable, and most importantly, I am free in all the ways that you are not. If not me — then who?</p>
        <button className="rv-btn rev" onClick={onClick}>{stage === 0 ? 'ARE YOU TYLER DURDEN?' : label}</button>
        <div className="rv-after">{after}</div>
      </div>
    </section>
  );
}
