// src/components/Soap.svelte
<section class="soap-sec sec" id="soap">
  <span class="eyebrow rev">// we make soap · 537 paper street</span>
  <div class="soap-grid" style="margin-top: 24px">
    <div>
      <svg class="soap-emblem rev" viewBox="0 0 400 300" fill="none">
        <text x="200" y="44" text-anchor="middle" fill="currentColor" font-family="'Special Elite',serif" font-size="34" letter-spacing="1">Paper Street Soap Co.</text>
        <ellipse cx="200" cy="160" rx="150" ry="78" stroke="currentColor" stroke-width="1.4" />
        <g stroke="currentColor" stroke-width="1.3" fill="none">
          <path d="M150 200 Q140 150 162 132 Q150 120 130 124 Q108 130 104 158 Q102 184 120 200" /><path d="M120 150 Q90 140 78 120 Q104 138 122 138" /><circle cx="158" cy="120" r="9" />
          <path d="M250 200 Q260 150 238 132 Q250 120 270 124 Q292 130 296 158 Q298 184 280 200" /><path d="M280 150 Q310 140 322 120 Q296 138 278 138" /><circle cx="242" cy="120" r="9" />
          <path d="M165 196 Q200 214 235 196 L228 178 L172 178 Z" /><path d="M200 178 L200 150 M188 160 Q200 146 212 160" /><path d="M196 138 Q200 128 204 138" />
        </g>
        <text x="200" y="262" text-anchor="middle" fill="currentColor" font-family="'Special Elite',serif" font-style="italic" font-size="16">All Natural · Handmade</text>
        <text x="200" y="284" text-anchor="middle" fill="currentColor" font-family="'Share Tech Mono',monospace" font-size="10" letter-spacing="2" opacity=".8">537 PAPER STREET · BRADFORD · (288) 555-0153</text>
      </svg>
      <p class="soap-txt rev">The first soap was made from the ashes of heroes. We make ours by hand, from the finest things we can find — rendered, salted, cured. Then sold back at a fair price to the very people it came from. There is a poetry to it, if you don&rsquo;t think about it too hard.</p>
      <p class="soap-meta rev">$20 A BAR · ALL NATURAL · HANDMADE · 537 PAPER STREET</p>
    </div>
    <div class="soap-card-img rev">
      <div class="polaroid">
        <span class="cork-pin"></span>
        <img src="img/soap-card.jpg" alt="Paper Street Soap Co. business card — the original prop" />
        <div class="hand">537 Paper Street · Bradford</div>
      </div>
    </div>
  </div>
</section>

// src/components/Soap.jsx
export default function Soap() {
  return (
    <section className="soap-sec sec" id="soap">
      <span className="eyebrow rev">// we make soap · 537 paper street</span>
      <div className="soap-grid" style={{ marginTop: 24 }}>
        <div>
          <svg className="soap-emblem rev" viewBox="0 0 400 300" fill="none">
            <text x="200" y="44" textAnchor="middle" fill="currentColor" fontFamily="'Special Elite',serif" fontSize="34" letterSpacing="1">Paper Street Soap Co.</text>
            <ellipse cx="200" cy="160" rx="150" ry="78" stroke="currentColor" strokeWidth="1.4" />
            <g stroke="currentColor" strokeWidth="1.3" fill="none">
              <path d="M150 200 Q140 150 162 132 Q150 120 130 124 Q108 130 104 158 Q102 184 120 200" /><path d="M120 150 Q90 140 78 120 Q104 138 122 138" /><circle cx="158" cy="120" r="9" />
              <path d="M250 200 Q260 150 238 132 Q250 120 270 124 Q292 130 296 158 Q298 184 280 200" /><path d="M280 150 Q310 140 322 120 Q296 138 278 138" /><circle cx="242" cy="120" r="9" />
              <path d="M165 196 Q200 214 235 196 L228 178 L172 178 Z" /><path d="M200 178 L200 150 M188 160 Q200 146 212 160" /><path d="M196 138 Q200 128 204 138" />
            </g>
            <text x="200" y="262" textAnchor="middle" fill="currentColor" fontFamily="'Special Elite',serif" fontStyle="italic" fontSize="16">All Natural · Handmade</text>
            <text x="200" y="284" textAnchor="middle" fill="currentColor" fontFamily="'Share Tech Mono',monospace" fontSize="10" letterSpacing="2" opacity=".8">537 PAPER STREET · BRADFORD · (288) 555-0153</text>
          </svg>
          <p className="soap-txt rev">The first soap was made from the ashes of heroes. We make ours by hand, from the finest things we can find — rendered, salted, cured. Then sold back at a fair price to the very people it came from. There is a poetry to it, if you don&rsquo;t think about it too hard.</p>
          <p className="soap-meta rev">$20 A BAR · ALL NATURAL · HANDMADE · 537 PAPER STREET</p>
        </div>
        <div className="soap-card-img rev">
          <div className="polaroid">
            <span className="cork-pin" />
            <img src="img/soap-card.jpg" alt="Paper Street Soap Co. business card — the original prop" />
            <div className="hand">537 Paper Street · Bradford</div>
          </div>
        </div>
      </div>
    </section>
  );
}
